# Generated by Django 5.2.1 on 2025-05-31 16:07

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ nhà tuyển dụng',
                'verbose_name_plural': 'Các hồ sơ nhà tuyển dụng',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Toàn thời gian'), ('Part-time', 'Bán thời gian'), ('Freelance', 'Tự do'), ('Intern', 'Thực tập')], default='Full-time', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Bản nháp'), ('Pending', 'Chờ duyệt'), ('Approved', 'Đã duyệt'), ('Rejected', 'Bị từ chối'), ('Expired', 'Hết hạn')], default='Draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('recruiter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='JobApp.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Tin tuyển dụng',
                'verbose_name_plural': 'Các tin tuyển dụng',
                'ordering': ['-created_at'],
            },
        ),
    ]
