# Generated by Django 5.2.1 on 2025-05-31 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Đã lên lịch'), ('Completed', 'Đã hoàn thành'), ('Canceled', 'Đã hủy')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phỏng vấn',
                'verbose_name_plural': 'Các buổi phỏng vấn',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Đã nộp hồ sơ'), ('Interview Scheduled', 'Đã lên lịch phỏng vấn'), ('Offered', 'Đã được đề nghị nhận việc'), ('Rejected', 'Bị từ chối'), ('Hired', 'Đã nhận việc'), ('Withdrawn', 'Rút hồ sơ')], default='Applied', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='JobApp.jobposting')),
            ],
            options={
                'verbose_name': 'Ứng tuyển',
                'verbose_name_plural': 'Các đơn ứng tuyển',
                'ordering': ['-applied_at'],
            },
        ),
    ]
